language: android
jdk: oraclejdk8

#android:
#    components:
#        - tools
#        - build-tools-25.0.2
#        - android-24
#        - extra-android-m2repository
#        - extra-google-m2repository

env:
    - ANDROID_HOME=$HOME/android-sdk

script:
    - ./gradlew build

before_install:
    - chmod +x gradlew
    - mkdir -p "$ANDROID_HOME/licenses"
    - mkdir -p "$HOME/android-sdk-dl"
    - mkdir -p "$HOME/android-sdk"
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install:
    # Download android SDK tools if not present
    - if test ! -e $HOME/android-sdk-dl/tools_r25.2.5-linux.zip; then curl https://dl.google.com/android/repository/tools_r25.2.5-linux.zip > $HOME/android-sdk-dl/tools_r25.2.5-linux.zip; fi
    - unzip -n $HOME/android-sdk-dl/tools_r25.2.5-linux.zip -d $HOME/android-sdk
    
    # Install/update SDK components
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;25.0.2'
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-24'
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;m2repository'
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository'

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution
    - rm -f $HOME/.gradle/caches/*/classAnalysis
    - rm -f $HOME/.gradle/caches/*/jarSnapshots

cache:
    directories:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/.android/build-cache
        - $HOME/android-sdk
        - $HOME/android-sdk-dl

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

branches:
    only:
        - master
        - Develop
